import React from "react";
import "../sass/termsConditions.css";

const TermsConditions = () => {
  return (
    <div className="container">
      <h1>TERMS &amp; CONDITIONS</h1>

      <div className="section">
        <p>
          These terms and conditions (&quot;Terms&quot;) governs you, the
          user&apos;s (&quot;User&quot; or &quot;You&quot; or &quot;Your&quot;
          or &quot;Yourself&quot;) participation in the Promotional Activity
          (defined hereunder) in and in connection with promotion/publicity of
          the fourth season of the series, Panchayat (&quot;Series&quot;) and
          shall be deemed a legal agreement between You and Amazon Seller
          Services Private Limited (&quot;Amazon&quot; / &quot;We&quot; /
          &quot;Us&quot; as applicable) with respect Your participation in the
          activity detailed hereunder as part of promotion and publicity for the
          Series (&quot;Promotional Activity&quot;). You agree and acknowledge
          that, by agreeing to participate in the Promotional Activity, You
          shall automatically be bound by these Terms. These Terms are, in
          addition to the conditions of use, available [at []](&quot;Conditions
          of Use&quot;) and the privacy notice, available at [] (&quot;Privacy
          Policy&quot;) of www.amazon.in and its corresponding mobile
          application/site, which you accept and agree to, by participating in
          this Promotional Activity. In the event you do not agree with these
          Terms, the Conditions of Use and Privacy Policy, please do not
          participate in the Promotional Activity. To the extent the Conditions
          of Use and/or Privacy Policy is inconsistent with these Terms; these
          Terms will prevail with respect to the Promotional Activity and only
          to the extent of such conflict. Notwithstanding anything contained in
          these Terms, Amazon has the right to discontinue/ postpone/ cancel the
          Promotional Activity and/or de-activate the Chatbot (defined below) at
          any time in its sole discretion without any prior notice and without
          liability.
        </p>

        <p>
          These Terms are an electronic record in terms of Information
          Technology Act, 2000 and rules thereunder (together the
          &quot;Act&quot;) as applicable and the amended provisions pertaining
          to electronic records in various statutes as amended by the
          Information Technology (Amendment) Act, 2008. This electronic record
          is generated by a computer system and does not require any physical or
          digital signatures.
        </p>
      </div>

      <h2>Tentative Description of the Promotional Activity:</h2>
      <div className="section">
        <p>
          The Promotional Activity is a WhatsApp-exclusive experience that
          simulates the User&apos;s entry into the world of &quot;Phulera&quot;.
          Users will be periodically thrown missions through text-based
          conversations via the WhatsApp messaging platform
          (&quot;Chatbot&quot;) which can be completed through texts with the
          Chatbot.
        </p>
      </div>

      <h3>Phase 1: Onboarding</h3>
      <div className="section">
        <p>
          The journey begins with the chatbot initiating a conversation, where
          different characters greet the user with a friendly &quot;Hi.&quot;
          The user is then prompted to share their name, gender, and a selfie.
          Once submitted, they receive a voter ID-style card marking their entry
          into the world of Phulera. This is followed by a recap of the show
          presented as a fun, interactive quiz. After completing the quiz, the
          user receives a personalized video message from the cast, encouraging
          them to pick their party. Once a party is selected, the user is
          awarded an official{" "}
          <span className="italic">&quot;Election Guru&quot;</span> certificate.
        </p>
      </div>

      <h3>Phase 2: Rally Song</h3>
      <div className="section">
        <p>
          The chatbot then shares a video clip and invites the user to be part
          of the viral <span className="italic">Rally Song</span>. On opting in,
          the user&apos;s selfie is used to create a personalized video using
          generative AI. Their face is superimposed onto a clone actor&apos;s
          body, integrating them directly into the scene alongside the lead
          characters. The final customized video is shareable via WhatsApp or
          any other platform as determined by Amazon.
        </p>
      </div>

      <h3>Phase 3: Mudda Kya Hai?</h3>
      <div className="section">
        <p>
          Next, the chatbot invites the user to support the election campaign
          through community service. The user is presented with three causes or
          situations to choose from. Based on their selection, generative AI
          incorporates their selfie into a themed image alongside cast members,
          placing them at the heart of the action.
        </p>
      </div>

      <h3>Phase 4: Poster Activity</h3>
      <div className="section">
        <p>
          In this phase, the chatbot prompts the user to select a campaign
          slogan for their party poster from three available options. Once
          selected, generative AI creates a personalized party poster featuring
          the user&apos;s selfie and chosen slogan. This poster is provided as a
          shareable asset for WhatsApp and other platforms.
        </p>
      </div>

      <h3>Phase 5: Jeet Ki Khushi Mein Shaamil Ho Jaao</h3>
      <div className="section">
        <p>
          To wrap up the experience, the chatbot sends a heartfelt message from
          a character&apos;s point of view, thanking the user for participating
          in all the election activities. The user then receives a
          name-personalized video, powered by generative AI, with the cast
          expressing their gratitude for making them their{" "}
          <span className="italic">&quot;Election Guru.&quot;</span> This video
          also includes a recap of all the personalized assets from the previous
          phases, creating a memorable and shareable finale to the WhatsApp
          election journey.
        </p>
      </div>

      <h2>Specific Terms:</h2>
      <div className="section">
        <ol className="terms-list">
          <li>
            User is required to submit their personal data including their name,
            phone number (linked to a WhatsApp account), and the Image via the
            Chatbot (the &quot;<span className="highlight">Entry</span>&quot;)
            during the Promotional Period only.
          </li>
          <li>
            The User may share such Personalized Audio Visual Materials on their
            personal social media handles along with the Promotional Activity
            hashtag as may be communicated to the User by Amazon from
            time-to-time, subject to the terms hereof.
          </li>
          <li>
            The User interaction in relation to the Promotional Activity shall
            be limited to maximum 20 per day.
          </li>
          <li>
            The Promotional Activity shall be conducted from 18<sup>th</sup>{" "}
            June 2025 onwards and shall continue till the time Amazon, at its
            sole discretion continues with the Promotional Activity (the &quot;
            <span className="highlight">Promotional Period</span>&quot;).
          </li>
          <li>
            Materials, Personalized Audio Visual Material and Meme shall
            collectively be referred to as &quot;
            <span className="highlight">Amazon Property</span>&quot;.
          </li>
        </ol>

        <p>
          Without limiting the generality of the foregoing, You agree that You
          are the owner or customary user of the mobile phone number, submitted
          as part of the Entry. Further, You agree that Your face is properly
          visible and understandable in the Image submitted as part of the
          Entry. Any Entry submitted after conclusion of the Promotional Period
          shall not be considered for the purposes of this Promotional Activity.
        </p>

        <p>
          Amazon and/or its affiliates shall not be responsible for any Entry
          submitted but not received or recorded due to any reason whatsoever.
          Without limiting the generality of the foregoing, Amazon and/or its
          affiliates shall not be responsible for technical errors of any nature
          whatsoever that results in an Entry not being received. Any automated
          receipt of confirmation does not constitute proof of actual receipt of
          the Entry.
        </p>
      </div>

      <h2>Grant of Rights:</h2>
      <div className="section">
        <ol className="terms-list">
          <li>
            You understand, agree and acknowledge that all rights in and to the
            Amazon Property are solely and exclusively owned and/or controlled
            by Amazon or its licensors for the period of perpetuity throughout
            the world. Save for as expressly provided herein, nothing in these
            Terms shall be construed to mean that You or any third party have
            any right, title or interest whatsoever in the Chatbot or the Amazon
            Property.
          </li>
          <li>
            By participating in the Promotional Activity and in consideration of
            mutual covenants and promises, You hereby grant Amazon and/ or its
            affiliates a perpetual, worldwide, non-exclusive right to use Your
            Image, name, face and/or likeness, any personal data submitted by
            you as part of the Entry and as may be embodied in the Amazon
            Property obtained and/or created in relation to the Promotional
            Activity including for any promotions, events, or contests to
            follow, if any (&quot;<span className="highlight">Attributes</span>
            &quot;) across all modes, mediums, and formats, whether the same is
            in existence now or devised/ invented in future, in any manner
            whatsoever. You hereby agree that Amazon and/ or its affiliates have
            the right to collect, store, process (including by way of automated
            technology) and/or publish Your Attributes including all information
            provided as part of the Entry and any other details regarding You in
            course of any communication, promotions, events, or contests that
            may follow. You acknowledge that You will not receive any
            compensation, etc. for Amazon&apos;s use of Your Attributes
            including the Image and hereby release Amazon and/ or its affiliates
            and its agents and assigns from any and all claims which arise out
            of or are in any way connected with such use of Your Attributes
            including the Image. You give Your consent and agree that Amazon
            and/or its affiliates, agents and assigns have the right but not the
            obligation to use and/or process (including by way of automated
            technology) Your Attributes including the Image in connection with
            the Promotional Activity and/or otherwise. It is further agreed that
            this licence shall not expire, terminate or be otherwise affected by
            the termination of these Terms, the termination or suspension of the
            Promotional Activity by Amazon or in any other circumstances.
          </li>
          <li>
            You hereby assign, grant, convey all rights, title, and interest,
            including rights in any form of intellectual property,
            performer&apos;s rights, copyright and rights in any form of
            exploitation in and to the Materials to Amazon, for the territory of
            the world and in perpetuity. Further, You agree that Sections 19(4)
            of the Copyright Act, 1957 (India) read with Section 30A of the
            Copyright Act, 1957 (India) do not apply to the assignment/licence
            granted herein to Amazon hereunder. In the event under operation of
            any law, the assignment herein is deemed not to apply to any future
            (and/or changed or new) means, methods (including technologies uses,
            media, versions, forms, formats, modes of transmission and methods
            of distribution, dissemination, exhibition or performance), mode or
            medium of the Materials or such mode or medium which is not in
            commercial use/ existence on the execution of this Agreement (&quot;
            <span className="highlight">Future Modes</span>&quot;), You hereby
            grant an irrevocable and exclusive license in perpetuity to Amazon,
            its transferees, assignees, and sub-licensees for the territory of
            the entire universe to exploit the Materials in any Future Modes, in
            consideration of mutual covenants and promises, the sufficiency of
            which is acknowledged by You. Parties agree that the assignment of
            the Materials shall apply for all modes, mediums and format, whether
            now known or hereinafter devised. Amazon shall have the right to
            exercise all rights comprised in copyright in the Materials pursuant
            to Section 14(1) (a) and (e) of the Copyright Act, 1957 or any other
            equivalent provision thereof. &quot;
            <span className="highlight">Materials</span>&quot; shall mean and
            include any literary works, performances, is and as applicable,
            including singing performances, musical works, lyrics, sound
            recordings, and other deliverables, as well as any other works of
            authorship (if any), intellectual property, drafts, revised drafts,
            final drafts or any other creations originated, prepared, created,
            suggested or devised by the Music Composer and all other results and
            proceeds of the Services, and shall include without limitation all
            scratches/tracks/sound recordings/musical works deliverables
            created, originated, prepared, suggested or devised by You, in
            connection with the Promotional Activity. The assignment of the
            Materials herein is not contrary to the provisions of Section 19(8)
            of the Copyright Act, 1957.
          </li>
          <li>
            Amazon grants You, a non-exclusive, non-transferrable, non-sub
            licensable, limited, personal right to download, use and/or share on
            an &apos;as is&apos; basis only, the Meme and/or Personalized Audio
            Visual Material, as applicable via Your personal social media
            handles, as applicable solely for non-commercial purposes and in all
            instances in accordance with these Terms.
          </li>
          <li>
            You agree and acknowledge that any uploads on the social media
            handles of the User and/or any third party authorized by the User
            shall not be blasphemous, indecent, immoral, abusive, offensive,
            against the applicable laws or libelous and/or is contrary to any
            law in force; disrepute the Series and/or Amazon in any manner
            whatsoever.
          </li>
          <li>
            You shall not claim ownership or dispute Amazon&apos;s ownership in
            and in relation to the Amazon Property. Creation of the Amazon
            Property using details, images, selfies provided by the User will
            not create any rights in favour of the User and User hereby
            irrevocably waives all so-called &quot;moral rights&quot; or
            &quot;droit moral&quot; rights and any similar or analogous rights
            to the maximum extent permitted under applicable law.
          </li>
        </ol>
      </div>

      <h2>Security:</h2>
      <div className="section">
        <p>
          You are prohibited from violating or attempting to violate the
          security of the Chatbot. You further agree and acknowledge that You
          shall not record, make copies, perform alterations, modifications,
          additions, distortions etc. to the any feature and service available
          through the Chatbot and publish the same in any form including its
          original and/or altered, modified, distorted form on any medium
          including voice record service, online platform, mobile application,
          over the top services and/or websites.
        </p>
      </div>

      <h2>User&apos;s Obligations and Undertakings:</h2>
      <div className="section">
        <p>
          By participating in the Promotional Activity, You agree and hereby
          represent/ warrant/ undertake:
        </p>

        <ol className="terms-list">
          <li>
            To provide true, accurate, current and complete information about
            Yourself as prompted by the Chatbot; You further provide Amazon with
            your consent to communicate with You and provide You information
            about the Amazon Property, Series, any products and/or services
            offered by Amazon including any other promotional activity whether
            or not in relation the said Series/Promotional Activity or
            otherwise, and any and all notifications/communications as Amazon
            may deem fit.
          </li>
          <li>
            Your participation in the Promotional Activity is on a voluntary and
            unsolicited basis; By participating in the Promotional Activity, You
            are willing to bear all risks, costs and consequences arising from
            such participation; You affirm that You are either 18 years or more
            of age and have read and understood the entire content of these
            Terms and Conditions and accept the same; You are fully entitled to
            enter into a valid agreement with Amazon and participate in the
            Promotional Activity and are not under any disability whether legal
            or contractual which prevents You from executing a valid agreement
            with Amazon and/or participating in.
          </li>
          <li>
            You may be disqualified from participating in the Promotional
            Activity for any reasons as determined by the Company, at its sole
            discretion includng in the event:
            <ul>
              <li>
                You do not follow and complete all of the steps set out in these
                Terms or do not fulfil the eligibility criteria; and
              </li>
              <li>
                You do not submit your Entry during the Promotional Period. Any
                Entry prior to or after the Promotion Period will not be
                considered and all such entries will be withdrawn from the
                Promotional Activity.
              </li>
            </ul>
          </li>
          <li>
            Your participation in the Promotional Activity, including in course
            of creation of the Amazon Property no material provided by You
            including the Image, selfie and/or the Entry, will contain any
            content that is blasphemous, indecent, immoral, abusive, offensive,
            against the applicable laws or libelous and/or is contrary to any
            law in force; is grossly harmful, harassing, defamatory, obscene,
            pornographic, paedophilic, libelous, invasive of another&apos;s
            privacy, hateful, or racially, ethnically objectionable,
            disparaging, relating or encouraging money laundering or gambling,
            or otherwise unlawful in any manner whatever; harms minors in any
            way; infringes any patent, trademark, copyright or other proprietary
            rights; or violates any law for the time being in force; deceives or
            misleads the addressee about the origin of such material or messages
            or communicates any information which is grossly offensive or
            menacing in nature; impersonate another person; contains software
            viruses or any other computer code, files or programs designed to
            interrupt, destroy or limit the functionality of any computer
            resource; threatens the unity, integrity, defence, security or
            sovereignty of India, friendly relations with foreign states, or
            public order or causes incitement to the commission of any
            cognizable offence or prevents investigation of any offence or is
            insulting any other nation;
          </li>
          <li>
            You will share your own image as part of the Entry for creation of
            the Amazon Property and shall not use the image of any third person,
            without the express permission of such third person. You will only
            use and/or share the Meme and/or Personalized Audio Visual Material
            in accordance with these Terms and there shall be no stand alone use
            of the Amazon Property in any manner. Amazon and/or its affiliates
            shall in no manner be responsible in the event the Personalized
            Audio Visual Material and/or Meme is not generated for You or there
            are any distortions to Your Attributes including the Image, selfie
            as are reflected in the Personalized Audio Visual Material and/or
            Meme.
          </li>
          <li>
            You will abide by all applicable laws and regulations when using the
            Chatbot and to not use the Chatbot and/or the Amazon Property for
            any illegal purpose;
          </li>
          <li>
            You will not transmit through the Chatbot any unlawful, unsolicited,
            abusive, threatening, obscene or otherwise objectionable material of
            any kind, or any material that violates the law or rights of a third
            party, including but not limited to the intellectual property rights
            of any third-party;
          </li>
          <li>
            You will not access or use the Chatbot, and/or take part in the
            Promotion Activity in any manner that could damage, disable,
            overburden or impair any of the Chatbot&apos;s servers or networks
            connected to any of the servers on which the Promotional Activity is
            hosted;
          </li>
          <li>
            You will not do any act either directly or indirectly which may
            bring Amazon and/or its affiliates into public disrepute, or offend
            any community or public morals;
          </li>
          <li>
            You shall be solely responsible for any and all costs and expenses
            that You may incur towards participating in this Promotional
            Activity. Amazon shall at no time be responsible for bearing any
            costs whatsoever. Amazon shall not be responsible for breach by a
            User of these Terms and such User shall indemnify Amazon against
            any/ all claims received due to such breach of these Terms.
          </li>
          <li>
            By using the Chatbot and participating in the Promotional Activity,
            You understand and acknowledge that Your internet service provider
            may impose standard browsing/surfing charges at all applicable rates
            which shall be borne solely by You. You shall be solely responsible
            for any and all costs and expenses that You may incur towards
            participating in this Promotional Activity. Amazon shall at no time
            be responsible for bearing any costs whatsoever.
          </li>
          <li>
            You agree and acknowledge that nothing contained herein or
            otherwise, imposes an obligation on Amazon to run the Chatbot and/or
            the Promotional Activity and/or generate a Personalized Audio Visual
            Material and/or Meme.
          </li>
          <li>
            Your usage of any social media platform and/or third party website
            including WhatsApp to participate in the Promotional Activity will
            be governed by the respective terms and conditions, terms of use and
            privacy policy of the respective social media platform and/or third
            party website including WhatsApp.
          </li>
        </ol>
      </div>

      <h2>Warranties and Indemnity:</h2>
      <div className="section">
        <ol className="terms-list">
          <li>
            Neither Amazon nor its affiliates, assigns, etc. shall be liable for
            any direct, indirect, consequential, special, exemplary or other
            damages that may result, including but not limited to economic loss,
            injury, illness or death. You alone are responsible and accountable
            for your decisions, actions and results in life and You agree not to
            attempt to hold us liable for any such decisions, actions or
            results, at any time, under any circumstances including based on
            your reliance of any interaction on the Chatbot.
          </li>
          <li>
            You agree that Your participation in the Promotional Activity shall
            be at Your sole risk. To the fullest extent permitted by law,
            Amazon, including its affiliates, and each of their respective
            officers, directors, employees, third party service providers, and
            agents disclaim all warranties, express or implied, in connection
            with the Promotional Activity.
          </li>
          <li>
            You agree to defend, indemnify and hold harmless Amazon, its
            affiliates and their respective officers, directors, employees and
            agents, from and against any and all claims, damages, obligations,
            losses, liabilities, costs or debt, and expenses (including but not
            limited to attorney&apos;s fees) arising from: (i) Your
            participation in the Promotional Activity; (ii) Your violation of
            any term of these Terms; or (iii) Your violation of any third party
            right, including without limitation any copyright, property, or
            privacy right; This defense and indemnification obligation will
            survive the efflux of time. You shall not in any circumstances make
            any claims against Amazon, their employees, directors and its
            affiliates arising out of or relating to any and all costs,
            injuries, losses or damages of any kind, including, without
            limitation due to any technical faults in the internet service
            provider&apos;s network and /or connections that may directly or
            indirectly affect Your use/ access of the Chatbot and/or Your
            participation or non-participation in the Promotional Activity in
            any manner whatsoever;
          </li>
          <li>
            To the maximum extent permitted by law, You agree to hereby
            irrevocably waive Your right to raise any dispute with regard to
            Your participation in the Promotional Activity, Your use/ access of
            the Chatbot and/or any other matter in connection therewith;
            Notwithstanding the foregoing, under no circumstances will Amazon be
            liable for any consequential, indirect, special, punitive, or
            incidental damages or lost profits, whether direct or indirect,
            arising in any way whether in contract, tort (including negligence)
            or otherwise. You specifically waive Your right to seek injunctive
            relief against Amazon and/or the Promotional Activity to the maximum
            extent permitted by law.
          </li>
        </ol>
      </div>

      <h2>Miscellaneous:</h2>
      <div className="section">
        <p>
          Amazon reserves the sole and exclusive right/s to make amendments to
          these Terms (and all the documents included by reference) including
          without limitation change the rules and structure of the Promotional
          Activity and the Chatbot without prior or subsequent notice, and Your
          continued use of the Chatbot and/or participation in the Promotional
          Activity following any amendment of these Terms shall signify Your
          assent to and acceptance of its revised terms. These Terms (and any
          part thereof), may not be transferred or assigned by You, but may be
          assigned by Amazon, without restriction. If any provision of these
          Terms are deemed invalid by any law or a court of competent
          jurisdiction, the invalidity of such provision shall not affect the
          validity of the remaining provisions of these Terms, which shall
          remain in full force and effect. No waiver of any term of these Terms
          shall be deemed a further or continuing waiver of such term or any
          other term, and Amazon&apos;s failure to assert any right or provision
          under these Terms shall not constitute a waiver of such right or
          provision. You acknowledge that the representations and warranties,
          indemnities, limitation of liability, governing law, dispute
          resolution, warranty disclaimer shall survive the efflux of time;
          Nothing herein shall be deemed to create a partnership, agency or an
          employer-employee relationship between You and Amazon. You acknowledge
          that in case the performance of this Promotional Activity is
          cancelled/postponed/abandoned including due to war, industrial action,
          flood or any Act of God or event beyond the reasonable control of
          Amazon then such non-performance or failure shall not be deemed as a
          breach by Amazon of these Term. Notwithstanding anything contained
          herein, Amazon shall have the sole right to re-schedule/ cancel/
          discontinue/ terminate the Promotional Activity and/or participation
          of a User forthwith and such decision shall be final and binding.
          Amazon shall not be responsible and/or liable in any manner whatsoever
          for any acts or omission of any third party service providers,
          including failure in receipt of/ delivery of any messages including
          network problems (including unclear network), breakdown of machinery,
          disruption in the network and/or the internet /network costs charged
          by the telecom/mobile/network operator etc. Any dispute in connection
          to the forgoing, shall be settled between You and the respective
          telecom/mobile operator/third party service provider directly, without
          involving Amazon. You shall not in any circumstances make any claims
          against Amazon, their employees, directors and its affiliates arising
          out of or relating to any and all costs, injuries, losses or damages
          of any kind, including, without limitation due to any technical faults
          in the network and /or connections or directly or indirectly due to,
          Your access to the Chatbot and/or Your participation or
          non-participation in the Promotional Activity
        </p>
      </div>

      <h2>Governing Law &amp; Jurisdiction:</h2>
      <div className="section">
        <p>
          The Promotional Activity and these Terms are governed by the laws of
          India. The Promotional Activity, Chatbot and all the accompanying
          materials are copyright of Amazon. All rights are reserved. Courts of
          Mumbai shall have the exclusive jurisdiction in respect of any
          disputes arising hereunder.
        </p>
      </div>
    </div>
  );
};

export default TermsConditions;
